force-app/main/default/objects/Guest_Pass__c/Guest_Pass__c.object-meta.xml
<CustomObject>
    <description>A pass for a single guest to visit Asphalt Green</description>
    <label>Guest Pass</label>
    <nameField>
        <displayFormat>AGPass-{00000000}</displayFormat>
        <label>Guest Pass Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guest Passes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Guest_Pass__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Guest Passes</relationshipLabel>
    <relationshipName>Guest_Passes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guest_Pass__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Valid&quot;</defaultValue>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issued</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Valid</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Guest_Pass__c/fields/Visit_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Visit_Date_Time__c</fullName>
    <description>The date/time that the guest pass was used to visit the facility</description>
    <inlineHelpText>The date/time that the guest pass was used to visit the facility</inlineHelpText>
    <label>Visit Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/GuestPassScannerController_Test.cls
@IsTest
private class GuestPassScannerController_Test {

    @IsTest
    static void testCheckInGuestPass() {
        Contact ct = TestDataFactory.createContacts(1).get(0);
        insert ct;

        Guest_Pass__c gp = new Guest_Pass__c();
        gp.Contact__c = ct.Id;
        gp.Status__c = GuestPassScannerController.STATUS_VALID;
        insert gp;

        String guestPassName = [SELECT Name FROM Guest_Pass__c WHERE Id = :gp.Id LIMIT 1].Name;

        String result;
        Test.startTest();
        result = GuestPassScannerController.checkInGuestPass(guestPassName);
        Test.stopTest();

        Assert.areEqual('Success', result, 'Should have received a successful message');

        Guest_Pass__c refreshedPass = [
            SELECT Status__c, Visit_Date_Time__c FROM Guest_Pass__c WHERE Id = :gp.Id LIMIT 1
        ];

        Assert.areEqual(GuestPassScannerController.STATUS_ATTENDED, refreshedPass.Status__c, 'Pass should have a status of Attended');
        Assert.isNotNull(refreshedPass.Visit_Date_Time__c, 'Pass should have a visit date/time');
    }

    @IsTest
    static void testCheckInAttendedGuestPass() {
        Contact ct = TestDataFactory.createContacts(1).get(0);
        insert ct;

        Guest_Pass__c gp = new Guest_Pass__c();
        gp.Contact__c = ct.Id;
        gp.Status__c = GuestPassScannerController.STATUS_ATTENDED;
        insert gp;

        String guestPassName = [SELECT Name FROM Guest_Pass__c WHERE Id = :gp.Id LIMIT 1].Name;

        String result;
        Test.startTest();
        result = GuestPassScannerController.checkInGuestPass(guestPassName);
        Test.stopTest();

        Assert.areNotEqual('Success', result, 'Should not have received a successful message');
    }

    @IsTest
    static void testCheckInInvalidPass() {
        String guestPassName = 'Bogus Guest Pass Name';

        String result;
        Test.startTest();
        result = GuestPassScannerController.checkInGuestPass(guestPassName);
        Test.stopTest();

        Assert.areNotEqual('Success', result, 'Should not have received a successful message');
    }
    
}